# Generated by Django 2.2 on 2021-10-15 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kwizwhiz_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['quiz']},
        ),
    ]
